### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'stop_words.txt'

### ISSUE THREAD

**Issue by Hemanth-Mydugolam** [sb0612/Sentence-Comparison-using-python-nltk#1]
error because of no text file in directory. which text file  i need to include?

**Comment by kinjalbasu** [comment]
Thanks for noticing!! I have uploaded a dummy stopword.txt. place the file with the .py file.
You can create your own stopword.txt. You can add less important words to the list.

There will be 3 arguments -
1 & 2 are two input sentence
3. important key-words that must be present in the compared sentence. The words with higher weight. keywords will be comma separated. 

I will upload a readme soon.
